[build]
    edge_functions="netlify/edge_functions"
    functions="netlify/functions"
    command=""
[[edge_functions]]
    pattern="/docs/frameworks-wrapper-for(angular|vue)
    function = "wrapper"
[[redirects]]
    from="docs/react-installation/"
    to="docs/react-data-grid/installation/"
    status = 301